---

- hosts: all
  become: true
  pre_tasks:

  - name: Instal updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Instal updates (Rocky)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package for Rocky
    tags: apache,httpd,rocky
    dnf:
      name: 
        - httpd
        - php-fpm
      state: latest
    when: ansible_distribution == "Rocky"

  - name: enable httpd
    tags: apache,httpd,rocky
    ansible.builtin.systemd_service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "Rocky"

  - name: allow httpd firewall
    tags: apache,httpd,rocky
    ansible.posix.firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true
    when: ansible_distribution == "Rocky"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0664

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (Rocky)
    tags: rocky,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

