---

- hosts: all
  become: true
  pre_tasks:

  - name: Instal updates (Ubuntu)
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Instal updates (Rocky)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php package for Ubuntu
      package:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php package for Rocky
      package:
        name: 
          - httpd
          - php-fpm
        state: latest
      when: ansible_distribution == "Rocky"

    - name: enable httpd
      ansible.builtin.systemd_service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "Rocky"

    - name: allow httpd firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      when: ansible_distribution == "Rocky"

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb package (Rocky)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

