- name: install apache and php package for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php package for Rocky
  tags: apache,httpd,rocky
  dnf:
    name: 
      - httpd
      - php-fpm
    state: latest
  when: ansible_distribution == "Rocky"

- name: change email address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin sysadmin@redstorm.com
  when: ansible_distribution == "Rocky"
  register: httpd

- name: restart httpd (Rocky)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: enable and start httpd (Rocky)
  tags: apache,httpd,rocky
  ansible.builtin.systemd_service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "Rocky"

- name: allow httpd firewall
  tags: apache,httpd,rocky
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  when: ansible_distribution == "Rocky"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664
