- name: install apache and php package for Ubuntu
  tags: apache,httpd,php
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: enable and start apache service
  tags: apache,http
  service:
    name: "{{ apache_package_name }}"
    state: started
    enabled: true

- name: change email address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin sysadmin@redstorm.com
  when: ansible_distribution == "Rocky"
  notify: restart_apache

- name: allow httpd firewall
  tags: apache,httpd,rocky
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
  when: ansible_distribution == "Rocky"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664
